---
{% raw %}
- hosts: all
  vars_files:
    - vars.yml

  tasks:
  - name: Install required system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: system_packages

  - name: Add repository key to keychain
    apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x5BB92C09DB82666C state=present

  - name: Add repository with Python 3.3 to apt resources list
    apt_repository: repo="deb http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu precise main"
  
  - name: Install Python 3.3 
    apt: pkg={{item}} update-cache=yes force=yes
    with_items: python_packages

  - name: Install setuptools
    shell: "wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python3.3"

  - name: Install pip
    easy_install: name=pip

  - name: Install pip packages
    pip: name={{item}}
    with_items: pip_packages

  - name: Install project as python package
    pip: name={{repository_root}} virtualenv={{venv_path}}

  - name: Install project requirements
    pip: requirements={{repository_root}}/requirements/{{settings}}.txt virtualenv={{venv_path}} virtualenv_command="virtualenv -p /usr/bin/python3.3"

  - name: Setup pg_hba file
    copy: src=conf/pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres group=postgres mode=0640
    register: pg_file

  - name: Reload postgres if it changed
    service: name=postgresql state=reloaded enabled=yes
    when: pg_file.changed

  - name: Create postgreSQL database
    postgresql_db: name="{{db_name}}"

  - name: Create postgreSQL user
    postgresql_user: db="{{db_name}}" name="{{db_user}}" password="CHANGEME" priv=ALL

  - name: Sync database
    django_manage: app_path={{project_root}} command=syncdb virtualenv={{venv_path}}
    
  - name: Copy nginx configuration file
    copy: src=conf/nginx.conf dest=/etc/nginx/sites-enabled/
    notify: restart nginx
 
  - name: Copy uwsgi configuration file
    copy: src=conf/uwsgi.ini dest=/etc/init
    notify: restart uwsgi

  - name: Copy uwsgi initialization script
    copy: src=conf/uwsgi_init.conf dest=/etc/init
    notify: restart uwsgi

  handlers:
    - include: handlers.yml
{% endraw %}
